<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Cool" ignored="0" name="Test" tests="7" failures="2" timestamp="14 May 2021 08:43:45 GMT" time="167.999" errors="0">
  <testcase name="InsurancePlanTest" time="20.997" classname="TestCase.TravelnsuranceTest"/>
  <testcase name="InsurancePlanTest" time="14.33" classname="TestCase.TravelnsuranceTest"/>
  <testcase name="InsurancePlanTest" time="7.057" classname="TestCase.TravelnsuranceTest">
    <failure type="java.lang.AssertionError" message="Failing the Test after capturing the error! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failing the Test after capturing the error! expected [true] but found [false]
at TestCase.TravelnsuranceTest.InsurancePlanTest(TravelnsuranceTest.java:72)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- InsurancePlanTest -->
  <testcase name="HealthInsuranceMenuTest" time="8.798" classname="TestCase.HealthInsuranceTest"/>
  <testcase name="CarInsuranceQuoteTest" time="21.626" classname="TestCase.CarInsuranceTest"/>
  <testcase name="CarInsuranceQuoteTest" time="17.501" classname="TestCase.CarInsuranceTest"/>
  <testcase name="CarInsuranceQuoteTest" time="69.719" classname="TestCase.CarInsuranceTest">
    <failure type="java.lang.AssertionError" message="Failing the Test after capturing the error! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Failing the Test after capturing the error! expected [true] but found [false]
at TestCase.CarInsuranceTest.CarInsuranceQuoteTest(CarInsuranceTest.java:72)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- CarInsuranceQuoteTest -->
</testsuite> <!-- Test -->
